routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */


Route::get('/',function()
{
   return "this is web application for SKBBL mobile app ";
});
 Auth::routes();
 Route::group(['middleware' => ['auth','permission:1']],function () 
 {
    Route::get('/butwal-home','Admin\OfficeDataController@butwalHome')->name('butwal-home'); 
    Route::get('/butwal-users','Admin\OfficeController@butwalUsers')->name('butwal-users');

    Route::get('/butwal-data','Admin\OfficeDataController@butwalData')->name('butwal-data');
    Route::get('/butwal-alldata','Admin\BackupDataController@btlallData')->name('butwal-alldata');
     Route::get('/butwal-notreceived',
       'Admin\OfficeDataController@butwalNotreceived')->name('butwal-notreceived');
  });
 Route::group(['middleware' => ['auth','permission:3']],function () 
 {
    Route::get('/pokhara-home', 'Admin\OfficeDataController@pkrHome')->name('pokhara-home');
    Route::get('/pokhara-users', 'Admin\OfficeController@pokharaUsers')->name('pokhara-users');
     Route::get('/pokhara-data','Admin\OfficeDataController@pkrData')->name('pokhara-data');
     Route::get('/pokhara-alldata','Admin\BackupDataController@pkrallData')->name('pokhara-alldata');
      Route::get('/pokhara-notreceived',
       'Admin\OfficeDataController@pkrNotreceived')->name('pokhara-notreceived');
 });
 Route::group(['middleware' => ['auth','permission:2']],function () 
 {
    Route::get('/admin-home', 'Admin\OfficeDataController@adminHome')->name('admin-home');
    Route::get('/admin-users', 'Admin\OfficeController@adminUsers')->name('admin-users');
     Route::get('/admin-data', 'Admin\OfficeDataController@adminData')->name('admin-data');
     Route::get('/admin-alldata','Admin\BackupDataController@adminallData')->name('admin-alldata');
     Route::get('/admin-notreceived',
       'Admin\OfficeDataController@adminNotreceived')->name('admin-notreceived');
  });
  Route::group(['middleware' => ['auth','permission:4']],function () 
  { 
    Route::get('/hetauda-home','Admin\OfficeDataController@htdHome')->name('hetauda-home'); 
    Route::get('/hetauda-users','Admin\OfficeController@htdUsers')->name('hetauda-users');

    Route::get('/hetauda-data','Admin\OfficeDataController@htdData')->name('hetauda-data');
    
    Route::get('/hetauda-alldata','Admin\BackupDataController@htdallData')->name('hetauda-alldata');
     Route::get('/hetauda-notreceived',
       'Admin\OfficeDataController@htdNotreceived')->name('hetauda-notreceived');
  });
   Route::group(['middleware' => ['auth','permission:5']],function () 
  { 
    Route::get('/gajuri-home','Admin\OfficeDataController@gjrHome')->name('gajuri-home'); 
    Route::get('/gajuri-users','Admin\OfficeController@gjrUsers')->name('gajuri-users');

    Route::get('/gajuri-data','Admin\OfficeDataController@gjrData')->name('gajuri-data');
    
    Route::get('/gajuri-alldata','Admin\BackupDataController@gjrallData')->name('gajuri-alldata');
     Route::get('/gajuri-notreceived',
       'Admin\OfficeDataController@gjrNotreceived')->name('gajuri-notreceived');
  });
   Route::group(['middleware' => ['auth','permission:6']],function () 
  { 
    Route::get('/bardibas-home','Admin\OfficeDataController@jkrHome')->name('bardibas-home'); 
    Route::get('/bardibas-users','Admin\OfficeController@jkrUsers')->name('bardibas-users');

    Route::get('/bardibas-data','Admin\OfficeDataController@jkrData')->name('bardibas-data');
    
    Route::get('/bardibas-alldata','Admin\BackupDataController@jkrallData')->name('bardibas-alldata');
     Route::get('/bardibas-notreceived',
       'Admin\OfficeDataController@jkrNotreceived')->name('bardibas-notreceived');
  });
   Route::group(['middleware' => ['auth','permission:7']],function () 
  { 
    Route::get('/itahari-home','Admin\OfficeDataController@itrHome')->name('itahari-home'); 
    Route::get('/itahari-users','Admin\OfficeController@itrUsers')->name('itahari-users');

    Route::get('/itahari-data','Admin\OfficeDataController@itrData')->name('itahari-data');
    
    Route::get('/itahari-alldata','Admin\BackupDataController@itrallData')->name('itahari-alldata');
     Route::get('/itahari-notreceived',
       'Admin\OfficeDataController@itrNotreceived')->name('itahari-notreceived');
  });
   Route::group(['middleware' => ['auth','permission:8']],function () 
  { 
    Route::get('/birtamod-home','Admin\OfficeDataController@btmHome')->name('birtamod-home'); 
    Route::get('/birtamod-users','Admin\OfficeController@btmUsers')->name('birtamod-users');

    Route::get('/birtamod-data','Admin\OfficeDataController@btmData')->name('birtamod-data');
    
    Route::get('/birtamod-alldata','Admin\BackupDataController@btmallData')->name('birtamod-alldata');
     Route::get('/birtamod-notreceived',
       'Admin\OfficeDataController@btmNotreceived')->name('birtamod-notreceived');
  });
   Route::group(['middleware' => ['auth','permission:9']],function () 
  { 
    Route::get('/surkhet-home','Admin\OfficeDataController@bdrHome')->name('surkhet-home'); 
    Route::get('/surkhet-users','Admin\OfficeController@bdrUsers')->name('surkhet-users');

    Route::get('/surkhet-data','Admin\OfficeDataController@bdrData')->name('surkhet-data');
    
    Route::get('/surkhet-alldata','Admin\BackupDataController@bdrallData')->name('surkhet-alldata');
     Route::get('/surkhet-notreceived',
       'Admin\OfficeDataController@bdrNotreceived')->name('surkhet-notreceived');
  });
   Route::group(['middleware' => ['auth','permission:10']],function () 
  { 
    Route::get('/attariya-home','Admin\OfficeDataController@attariyaHome')->name('attariya-home'); 
    Route::get('/attariya-users','Admin\OfficeController@atrUsers')->name('attariya-users');

    Route::get('/attariya-data','Admin\OfficeDataController@attariyaData')->name('attariya-data');
    
    Route::get('/attariya-alldata','Admin\BackupDataController@atrallData')->name('attariya-alldata');
     Route::get('/attariya-notreceived',
       'Admin\OfficeDataController@attariyaNotreceived')->name('attariya-notreceived');
  });
   Route::group(['middleware' => ['auth','permission:11']],function () 
  { 
    Route::get('/nepalgunj-home','Admin\OfficeDataController@npjHome')->name('nepalgunj-home'); 
    Route::get('/nepalgunj-users','Admin\OfficeController@npjUsers')->name('nepalgunj-users');

    Route::get('/nepalgunj-data','Admin\OfficeDataController@npjData')->name('nepalgunj-data');
    
    Route::get('/nepalgunj-alldata','Admin\BackupDataController@npjallData')->name('nepalgunj-alldata');
     Route::get('/nepalgunj-notreceived',
       'Admin\OfficeDataController@npjNotreceived')->name('nepalgunj-notreceived');
  });
  Route::group(['middleware' => ['auth','permission:12']],function () 
  { 
    Route::get('/unit-home','Admin\OfficeDataController@unitHome')->name('unit-home'); 
    Route::get('/unit-users','Admin\OfficeController@unitUsers')->name('unit-users');

    Route::get('/unit-data','Admin\OfficeDataController@unitData')->name('unit-data');
    
    Route::get('/unit-alldata','Admin\BackupDataController@unitallData')->name('unit-alldata');
     Route::get('/unit-notreceived',
       'Admin\OfficeDataController@unitNotreceived')->name('unit-notreceived');
  });


Route::group(['middleware' => ['auth']],function () {
  
    Route::prefix('admin')->group(function(){
      Route::get('/changePassword', 'HomeController@showChangePasswordForm');
      Route::post('/changePassword', 'HomeController@changePassword')->name('changePassword');
      Route::get('/list', 'Auth\RegisterController@list')->name('users.list');
      Route::post('/import-user','Auth\RegisterController@importOffice')->name('importuser');

    });
  });
   Route::group(['middleware' => ['auth']],function () {

    Route::resource('offices','Admin\OfficeController')->only(['edit', 'update']);
     Route::resource('officedata','Admin\OfficeDataController');
   });
  
  Route::group([ 'namespace' => 'Admin'],function () {
       Route::prefix('admin')->group(function(){
        Route::get('/areadata/{id}','OfficeDataController@databyArea')->name('areadata.show');
       
       
        Route::get('/notreceived','OfficeDataController@notreceived')->name('notreceived');
        Route::get('/received','OfficeDataController@received')->name('received');
        Route::get('/areareceived/{areadata}','OfficeDataController@areareceived')->name('areareceived');
        Route::get('/areanotreceived/{areadata}','OfficeDataController@areanotreceived')->name('areanotreceived');
        Route::post('/get-data','BackupDataController@getdata')->name('get-data');
        Route::get('/all-data','BackupDataController@index')->name('all-data');
        Route::get('/data-index','BackupDataController@allData')->name('data-index');

      });
    });

       //export/import  to excel
    Route::group([ 'namespace' => 'Admin'],function () {
      Route::prefix('admin')->group(function(){
        Route::get('/downlaod-excel','OfficeController@export')->name('downloadinfo');
        Route::get('/export-excel','OfficeDataController@export')->name('exportdata');
        Route::get('/export-received','OfficeDataController@exportreceived')->name('exportreceived');
        Route::get('/export-area/{areadata}','OfficeDataController@exportbyarea')->name('exportbyarea');
        Route::post('/import-office','OfficeController@importData')->name('import');

      });
    });

});

resources/views/jkr/activedata.blade.php
@extends('layouts.jkr-app')
@section('content')
<div class="content-wrapper">
 <div>
  <center>

   <span><strong><?php echo date('Y-m-d') ?></strong></span> <br/>
   <span><strong>Data Summary  of <?php echo $finaldate ?></strong></span>
    <br/><br/>
   <span class="btn btn-danger">Total:{{ $office->count() }}</span>&nbsp
   <a href="{{ route('received') }}" class="btn btn-success">Received:{{ $data->count() }}</a>&nbsp
   <a href = "{{ route('butwal-notreceived') }}" class="btn btn-secondary">Not Received:{{ $office->count() - $data->count() }}</a>
  </center>
 </div>
 <table id="example" class="table table-striped table-bordered" style="width:100%">
      <thead>
        <tr  style="font-size: 12px;">
        <th>क्र.स</th>
        <th>आर्थिक बर्ष</th>
        <th>महिना</th>
        <th>संस्था</th>
        <th>ईलाका कार्यालय</th>
        <th>दलित पुरुष सदस्य</th>
        <th>दलित महिला सद्स</th>
        <th>जनजाती पुरुष सद्स्य</th>
        <th>जनजाती महिला सद्स्य </th>
        <th>अन्य पुरुष सद्स्य </th>
        <th>अन्य महिला सद्स्य </th>
        <th>जम्मा सद्स्य</th>
        <th>ऋणी पुरुष सदस्य  </th>
        <th>ऋणी महिला सदस्य </th>
        <th>जम्मा ऋणी सदस्य </th>
        <th>ल . र .र </th>
        <th>लगानी </th>
        <th>सावा असुली  </th>
        <th>ब्याज असुली </th>
        <th>भाका नाघेको रकम </th>
        <th>पाउनु पर्ने बाकी ब्याज</th>
        <th>आन्तरिक श्रोत सेयर पुजी </th>
        <th>आन्तरिक श्रोत जगेडा कोस   </th>
        <th>आन्तरिक श्रोत समुह बचत  </th>
        <th>आन्तरिक श्रोत अन्य </th>
        <th>जम्मा आन्तरिक श्रोत पुजी </th>
        <th>साना किसान बैंक बाट लिएको ऋण</th>
        <th>साना किसान बैंक लाई बुझाएको ऋण </th>
        <th>साना किसान बैंक लाई तिर्न बाँकी  ऋण </th>
        <th>अन्य बाट लिएको  ऋण </th>
        <th>अन्य लाई बुझाएको ऋण </th>
        <th>अन्य लाई तिर्न बाँकी ऋण </th>
        <th> जम्मा ऋण </th>
        <th>ब्याज आमदानी</th>
        <th>अन्य आमदानी </th>
        <th> जम्मा आम्दानी </th>
        <th>ब्याज खर्च </th>
        <th>कर्मचारी प्रसासनिक खर्च </th>
        <th>जोखिम कोश खर्च </th>
         <th> जम्मा खर्च</th>
        <th> नाफा नोक्सान</th>
       </tr>
      </thead>
      <tbody>
      @foreach($data as $datas)
        <tr style="font-size: 11px;">
         <td> {{ $datas->id }}</td>
         <td>{{ $datas->fiscal_year }}</td>
         <td> @if($datas->month == "1" ) Baisakh
              @elseif($datas->month == "2") Jestha
              @elseif($datas->month == "3") Ashar
              @elseif($datas->month == "4") Shrawan
              @elseif($datas->month == "5") Bhadra
              @elseif($datas->month == "6") Ashoj
              @elseif($datas->month == "7") Kartik
              @elseif($datas->month == "8") Mangsir
              @elseif($datas->month == "9") Poush
              @elseif($datas->month == "10") Magh
              @elseif($datas->month == "11") Falgun
              @elseif($datas->month == "12") Chait
              @endif
        </td>
         <td>{{ $datas->office->coperative_name }}</td>
         <td>{{ $datas->area->name }}</td>
         <td>{{ $datas->member_dalit_male }}</td>
         <td>{{ $datas->member_dalit_female }}</td>
         <td>{{ $datas->member_janajati_male }}</td>
         <td>{{ $datas->member_janajati_female }}</td>
         <td>{{ $datas->member_other_male }}</td>
         <td>{{ $datas->member_other_female }}</td>
         <td>{{ $datas->total_member }}</td>
         <td>{{ $datas->loaned_male_number }}</td>
         <td>{{ $datas->loaned_female_number }}</td>
         <td>{{ $datas->total_loaned_people }}</td>
         <td>{{ $datas->laganima_raheko_rakam }}</td>
         <td>{{ $datas->lagani }}</td>
         <td>{{ $datas->sewa_asuli }}</td>
         <td>{{ $datas->byaj_asuli }}</td>
         <td>{{ $datas->vaka_nageko_rakam }}</td>
         <td>{{ $datas->paunu_parne__baki_byaj }}</td>
         <td>{{ $datas->antarik_source_share_pungi }}</td>
         <td>{{ $datas->antarik_source_jageda_kosh }}</td>
         <td>{{ $datas->antarik_source_samuha_bachat }}</td>
         <td>{{ $datas->antarik_source_other }}</td>
         <td>{{ $datas->total_antarik_source_pungi }}</td>
         <td>{{ $datas->skbbl_bata_lieko_loan}}</td>
         <td>{{ $datas->skbbl_lai_bujaeko_loan }}</td>
         <td>{{ $datas->skbbl_lai_tirna_baki_loan }}</td>
         <td>{{ $datas->aru_bata_lieko_loan }}</td>
         <td>{{ $datas->aru_lai_bujaeko_loan }}</td>
         <td>{{ $datas->aru_lai_tirna_baki_loan }}</td>
         <td>{{ $datas->total_external_loan }}</td>
         <td>{{ $datas->byaj_income }}</td>
         <td>{{ $datas->other_income }}</td>
         <td>{{ $datas->total_income }}</td>
         <td>{{ $datas->byaj_expense }}</td>
         <td>{{ $datas->karmachari_parsasanik_expense }}</td>
         <td>{{ $datas->jokhim_kosh_expense }}</td>
         <td>{{ $datas->total_expense }}</td>
         <td>{{ $datas->profit_loss }}</td>

      </tr>
      @endforeach
      </tbody>
  </table>
</div>
@endsection

resources/views/jkr/alldata.blade.php
@extends('layouts.jkr-app')
@section('content')
<div class="content-wrapper" ;>
 <div>
  <center>
    <span><strong><?php echo date('Y-m-d') ?></strong></span> <br/>
    <span><strong></strong></span>
    <br/><br/>
  </center>
 </div>
 <table id="alldata" class="table table-striped table-bordered" style="width:100%">
      <thead>
        <tr  style="font-size: 12px;">
        <th>क्र.स</th>
        <th>आर्थिक बर्ष</th>
        <th>महिना</th>
        <th>संस्था</th>
        <th>Action</th>
        <th>ईलाका कार्यालय</th>
        <th>दलित पुरुष सदस्य</th>
        <th>दलित महिला सद्स</th>
        <th>जनजाती पुरुष सद्स्य</th>
        <th>जनजाती महिला सद्स्य </th>
        <th>अन्य पुरुष सद्स्य </th>
        <th>अन्य महिला सद्स्य </th>
        <th>जम्मा सद्स्य</th>
        <th>ऋणी पुरुष सदस्य  </th>
        <th>ऋणी महिला सदस्य </th>
        <th>जम्मा ऋणी सदस्य </th>
        <th>ल . र .र </th>
        <th>लगानी </th>
        <th>सावा असुली  </th>
        <th>ब्याज असुली </th>
        <th>भाका नाघेको रकम </th>
        <th>पाउनु पर्ने बाकी ब्याज</th>
        <th>आन्तरिक श्रोत सेयर पुजी </th>
        <th>आन्तरिक श्रोत जगेडा कोस   </th>
        <th>आन्तरिक श्रोत समुह बचत  </th>
        <th>आन्तरिक श्रोत अन्य </th>
        <th>जम्मा आन्तरिक श्रोत पुजी </th>
        <th>साना किसान बैंक बाट लिएको ऋण</th>
        <th>साना किसान बैंक लाई बुझाएको ऋण </th>
        <th>साना किसान बैंक लाई तिर्न बाँकी  ऋण </th>
        <th>अन्य बाट लिएको  ऋण </th>
        <th>अन्य लाई बुझाएको ऋण </th>
        <th>अन्य लाई तिर्न बाँकी ऋण </th>
        <th> जम्मा ऋण </th>
        <th>ब्याज आमदानी</th>
        <th>अन्य आमदानी </th>
        <th> जम्मा आम्दानी </th>
        <th>ब्याज खर्च </th>
        <th>कर्मचारी प्रसासनिक खर्च </th>
        <th>जोखिम कोश खर्च </th>
         <th> जम्मा खर्च</th>
        <th> नाफा नोक्सान</th>
       </tr>
      </thead>
      <tbody>
      @foreach($data as $datas)
        <tr style="font-size: 11px;">
         <td> {{ $datas->id }}</td>
         <td>{{ $datas->fiscal_year }}</td>
         <td> @if($datas->month == "1" ) Baisakh
              @elseif($datas->month == "2") Jestha
              @elseif($datas->month == "3") Ashar
              @elseif($datas->month == "4") Shrawan
              @elseif($datas->month == "5") Bhadra
              @elseif($datas->month == "6") Ashoj
              @elseif($datas->month == "7") Kartik
              @elseif($datas->month == "8") Mangsir
              @elseif($datas->month == "9") Poush
              @elseif($datas->month == "10") Magh
              @elseif($datas->month == "11") Falgun
              @elseif($datas->month == "12") Chait
              @endif
        </td>
         <td>{{ $datas->office->coperative_name }}</td>
         <td>
            <a href ="{{ route('officedata.edit',$datas->id) }}" ><span class="btn btn-danger btn-sm">EDIT</span></a>
            
         </td>
         <td>{{ $datas->area->name }}</td>
         <td>{{ $datas->member_dalit_male }}</td>
         <td>{{ $datas->member_dalit_female }}</td>
         <td>{{ $datas->member_janajati_male }}</td>
         <td>{{ $datas->member_janajati_female }}</td>
         <td>{{ $datas->member_other_male }}</td>
         <td>{{ $datas->member_other_female }}</td>
         <td>{{ $datas->total_member }}</td>
         <td>{{ $datas->loaned_male_number }}</td>
         <td>{{ $datas->loaned_female_number }}</td>
         <td>{{ $datas->total_loaned_people }}</td>
         <td>{{ $datas->laganima_raheko_rakam }}</td>
         <td>{{ $datas->lagani }}</td>
         <td>{{ $datas->sewa_asuli }}</td>
         <td>{{ $datas->byaj_asuli }}</td>
         <td>{{ $datas->vaka_nageko_rakam }}</td>
         <td>{{ $datas->paunu_parne__baki_byaj }}</td>
         <td>{{ $datas->antarik_source_share_pungi }}</td>
         <td>{{ $datas->antarik_source_jageda_kosh }}</td>
         <td>{{ $datas->antarik_source_samuha_bachat }}</td>
         <td>{{ $datas->antarik_source_other }}</td>
         <td>{{ $datas->total_antarik_source_pungi }}</td>
         <td>{{ $datas->skbbl_bata_lieko_loan}}</td>
         <td>{{ $datas->skbbl_lai_bujaeko_loan }}</td>
         <td>{{ $datas->skbbl_lai_tirna_baki_loan }}</td>
         <td>{{ $datas->aru_bata_lieko_loan }}</td>
         <td>{{ $datas->aru_lai_bujaeko_loan }}</td>
         <td>{{ $datas->aru_lai_tirna_baki_loan }}</td>
         <td>{{ $datas->total_external_loan }}</td>
         <td>{{ $datas->byaj_income }}</td>
         <td>{{ $datas->other_income }}</td>
         <td>{{ $datas->total_income }}</td>
         <td>{{ $datas->byaj_expense }}</td>
         <td>{{ $datas->karmachari_parsasanik_expense }}</td>
         <td>{{ $datas->jokhim_kosh_expense }}</td>
         <td>{{ $datas->total_expense }}</td>
         <td>{{ $datas->profit_loss }}</td>

      </tr>
      @endforeach
      </tbody>
 </table>

</div>
@endsection

resources/views/jkr/home.blade.php
@extends('layouts.jkr-app')
@section('content')
<div class="content-wrapper">
  <div class="container-fluid">
   <div class="row">
    
    <div class="col-sm-3">
      <div class="card text-white bg-primary mb-3" style="max-width: 14rem;max-height: 10rem;">
          <div class="card-header">Butwal</div>
          <div class="card-body" style="color:black; background-color:lightblue;">
  
          </div>
         </div>
   </div>   
  </div>
</div>
</div>
@endsection

resources/views/jkr/notreceived.blade.php
@extends('layouts.jkr-app')
@section('content')
<div class="content-wrapper">
 
<table id="example" class="table table-striped table-bordered" style="width:100%">
      <thead>
       <tr>
        <th>Id</th>
        <th>Coperative </th>
        <th>status</th>
        <th>Mobile Number</th>
        <th>Area</th>
       </tr>
      </thead>
      <tbody>
      @foreach($notreceived as $datas)
        <tr>
         <td> {{ $datas->id }}</td>
         <td>{{ $datas->coperative_name }}</td>
         <td><span class="btn btn-secondary">Inactive</span></td>
         <td>{{ $datas->mobile_no }}</td>
         <td>{{ $datas->area->name }}</td>
      </tr>
      @endforeach
      </tbody>
  </table>
</div>
@endsection

resources/views/jkr/office.blade.php
@extends('layouts.jkr-app')
@section('content')
<div class="content-wrapper">
  <div>
           <center><h4> All Coperatives info</h4></center>
     <center><a href = "{{ route('downloadinfo') }}" class="fa fa-download btn btn-success ">Excel</a></center>
        <div class="card-body">
            <form action="{{ route('import') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <input type="file" name="file" class="form-control" required>
                <br>
                <button class="btn btn-success">Import Office Info</button>
            </form>
        </div>
  </div>
  <table id="alldata" class="table table-striped table-bordered" style    ="width:100%">
      <thead>
       <tr style="font-size: 12px;">
        <th>Id</th>
        <th>संस्थाको नाम</th> 
         <th>Username</th>
          <th> Action </th>
         <th>Password</th>
         <th>मोबाईल न.</th>
        <th>संस्थाको प्रकार</th>
        <th>स्थाइ लेखा नंबर</th>
        <th>इलाका कार्यालय</th>
        <th>प्रदेश</th>
        <th>जिल्ला </th>
        <th>पालिका</th>
        <th>पालिकाको प्रकार </th>
        <th>वार्ड नं.</th>
        <th>status</th>
       </tr>
      </thead>
      <tbody>
       
        @foreach($user as $offices)
        <tr style="font-size: 11px;">
        <td>{{ $offices->id }}</td>
        <td>{{ $offices->coperative_name}}</td>
        <td>{{ $offices->user['username'] }}</td>
         <td><a href ="{{ route('offices.edit',$offices->id) }}" ><span class="btn btn-danger btn-sm">EDIT</span></td>
        <td>{{ $offices->user['password'] }}</td>
         <td>{{ $offices->mobile_no }}</td>
        <td>@if($offices->coperative_type == 1)<span>SFCL</span>
            @elseif($offices->coperative_type == 2)<span>Other</span>
            @endif
        </td>
        <td>{{ $offices->pan_no }}</td>
        <td>{{ $offices->area->name }}
        <td>{{ $offices->province }}</td>
        <td>{{ $offices->district }}</td>
        <td>{{ $offices->palika }}</td>
        <td> @if($offices->palika_type == 1)<span>महानगरपालिका</span>
            @elseif($offices->palika_type == 2)<span>उपमहानगरपालिका</span>
              @elseif($offices->palika_type == 3)<span>नगरपालिका</span>
              @elseif($offices->palika_type == 4)<span>गाउँपालिका </span>
              @endif
        </td>
        <td>{{ $offices->ward_no }}</td>
        <td> @if($offices->user['status'] == 1)<span class="btn btn-warning">Active</span>
            @elseif($offices->user['status'] == 0)<span class="btn btn-secondary">Inactive </span>
            @endif
        </td>
        </tr>
        @endforeach
        
      </tbody>
  </table>

</div>
@endsection